"""Report rendering.

Two forms, because they serve different readers: JSONL for machines and downstream tooling, and
Markdown for a person.

The Markdown report leads with what was **verified**. Conforming documents may legitimately agree
everywhere, and a report that opens with an empty findings list reads as a broken tool rather than
as a clean result -- so the verification table is the headline and the findings follow it.
"""

from __future__ import annotations

import json
from pathlib import Path

from pidgraph.crossref.checks import CrossReferenceReport, Severity

_SEVERITY_ORDER = {
    Severity.CRITICAL: 0,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
    Severity.INFO: 4,
}


def write_jsonl(report: CrossReferenceReport, path: str | Path) -> Path:
    """One finding per line, ordered by severity. Stable across runs."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    ordered = sorted(report.findings, key=lambda f: (_SEVERITY_ORDER[f.severity], f.check, f.title))
    with p.open("w", encoding="utf-8") as handle:
        for finding in ordered:
            handle.write(json.dumps(finding.to_dict(), sort_keys=True) + "\n")
    return p


def render_markdown(
    report: CrossReferenceReport,
    *,
    pid_source: str,
    sop_source: str,
    sop_title: str = "",
    extraction: dict | None = None,
) -> str:
    """Render a human-readable report."""
    lines: list[str] = []
    add = lines.append

    add("# P&ID / SOP Cross-Reference Report")
    add("")
    add(f"- **Drawings:** `{pid_source}`")
    add(f"- **Procedure:** `{sop_source}`" + (f" — *{sop_title}*" if sop_title else ""))
    if report.extraction_recall is not None:
        add(f"- **Estimated extraction recall:** {report.extraction_recall:.0%}")
    add("")

    verified = report.verified
    issues = report.issues
    by_severity = report.by_severity()

    add("## Summary")
    add("")
    add(f"**{len(verified)} checks verified** · **{len(issues)} findings**")
    if by_severity:
        add("")
        add("| Severity | Count |")
        add("|---|---|")
        for severity, count in sorted(by_severity.items(), key=lambda kv: kv[0]):
            add(f"| {severity} | {count} |")
    add("")

    # Verified first. A conforming pair of documents agrees, and that is a result.
    if verified:
        add("## Verified")
        add("")
        add("These checks ran and found agreement. They are listed in full, because otherwise a")
        add("clean result would look exactly like a tool that did nothing.")
        add("")
        add("| Check | Subject | Outcome |")
        add("|---|---|---|")
        for finding in verified:
            subject = finding.subject or "—"
            add(f"| `{finding.check}` | {subject} | {finding.title} |")
        add("")

    if issues:
        add("## Findings")
        add("")
        for finding in sorted(issues, key=lambda f: (_SEVERITY_ORDER[f.severity], f.check)):
            marker = "⚠" if finding.severity in (Severity.CRITICAL, Severity.HIGH) else "•"
            add(f"### {marker} {finding.title}")
            add("")
            add(f"- **Check:** `{finding.check}`")
            add(f"- **Severity:** {finding.severity} · **Status:** {finding.status}")
            add(f"- **Confidence:** {finding.confidence:.0%}")
            if finding.sop_evidence:
                add(f"- **Procedure evidence:** {finding.sop_evidence}")
            if finding.pid_evidence:
                add(f"- **Drawing evidence:** {finding.pid_evidence}")
            if finding.graph_incomplete:
                add(
                    "- ⓘ This finding rests on something *not* being found. That could mean the "
                    "document has a defect, or it could just mean extraction missed it — which "
                    "cannot be distinguished, so the severity is capped."
                )
            add("")
            add(finding.detail)
            add("")
    else:
        add("## Findings")
        add("")
        add("None — every check that ran agreed. The verification table above shows which ones.")
        add("")

    if extraction:
        add("## Extraction")
        add("")
        add("| Metric | Value |")
        add("|---|---|")
        for key, value in extraction.items():
            add(f"| {key} | {value} |")
        add("")

    if report.notes:
        add("## Notes")
        add("")
        for note in report.notes:
            add(f"- {note}")
        add("")

    add("---")
    add("")
    add(
        "*Generated by deterministic rules. The same inputs produce the same "
        "report, character for character.*"
    )
    add("")
    return "\n".join(lines)


def write_markdown(text: str, path: str | Path) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    return p
